 const About=()=>{
    return(
<div>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egestas sit amet mauris id placerat. Morbi fermentum ligula vel nunc tempus, a aliquam nisi convallis. Sed ex ante, tristique a est nec, dapibus auctor leo. Fusce feugiat tortor et efficitur sodales. Donec at est a arcu suscipit porttitor nec sed dolor. Morbi rhoncus justo dui, non volutpat leo aliquam vitae. Duis molestie tellus id viverra ullamcorper. Nam sit amet elit magna. Integer at odio tempor, rhoncus purus et, egestas ligula.

Phasellus ac justo lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam euismod enim velit, sit amet tristique augue vehicula eget. Suspendisse turpis orci, egestas a ligula sit amet, elementum maximus orci. Nulla feugiat purus sit amet felis tincidunt, a facilisis odio elementum. Aenean ultricies, risus non ullamcorper auctor, nibh ex lacinia purus, eget vehicula ipsum nisi non erat. In dolor lectus, aliquet euismod gravida et, aliquet sit amet mi. Integer eu nulla erat.

Morbi placerat tellus a libero aliquet maximus. Suspendisse eget bibendum augue. Maecenas posuere mi vel dui placerat, in placerat dolor volutpat. Praesent ac ipsum lorem. Sed quis vulputate libero, a ultrices mi. Integer diam lacus, rhoncus at lorem id, viverra lacinia velit. Vivamus fringilla mauris et quam ultrices scelerisque. Phasellus ut feugiat justo. Maecenas venenatis eleifend urna, sit amet efficitur massa. Morbi lobortis nec felis id dapibus. Etiam pellentesque turpis eros, non vestibulum metus eleifend a. Aliquam ultricies turpis vel velit mattis, et dictum lacus hendrerit. Vivamus turpis lorem, sagittis sed est vitae, sollicitudin rutrum justo. Nulla a sagittis eros.

Cras sollicitudin dolor nec lectus sagittis, vitae volutpat est sollicitudin. Sed ut purus tempor, sagittis lectus sit amet, porta magna. Morbi dictum quam sit amet ex euismod interdum. Vestibulum convallis, augue id elementum mattis, libero velit commodo dolor, in maximus augue ante quis metus. Nullam sagittis quis enim at molestie. Quisque tempus bibendum mauris, a volutpat velit convallis eget. Pellentesque eget eros finibus sapien blandit ullamcorper eget id massa. Curabitur egestas, nulla nec aliquet varius, lacus est varius felis, venenatis ornare justo enim sit amet neque. Mauris sed commodo est. Donec a felis auctor ex tincidunt dictum a nec lacus. Vivamus vel vulputate ante.

Nunc semper ante vestibulum mi ultricies vulputate. Quisque ultricies lacinia enim nec finibus. Curabitur tincidunt massa vel varius vulputate. Pellentesque efficitur vel ligula eu volutpat. Vivamus id pharetra felis. Aliquam dictum metus et varius vulputate. Donec dictum vel quam et finibus. Praesent auctor sollicitudin justo vitae tristique. Proin sodales dapibus turpis, id rhoncus lectus aliquet sed. Praesent lorem massa, rhoncus at elementum ac, congue quis nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas cursus rutrum felis vitae porttitor. Maecenas iaculis nisi sed nisl eleifend faucibus. Proin id sem vel orci elementum varius eget nec lorem. Etiam ac turpis velit. Duis vitae pretium ex.

Pellentesque placerat elit nec orci aliquam, rhoncus tempus eros varius. Aliquam mattis congue felis, quis dignissim ex porta at. Donec scelerisque vestibulum massa, at maximus tortor interdum vel. Nunc in ipsum ut ex malesuada finibus. Integer ac libero tortor. Nam consectetur quis urna elementum consectetur. Suspendisse dapibus quam vel turpis lacinia, sed laoreet magna venenatis. Sed dignissim odio a eros finibus, quis efficitur elit lobortis. Donec id finibus purus, quis viverra felis. Nulla porta faucibus ex quis blandit. Mauris sollicitudin consectetur ligula. Ut molestie sed metus sed accumsan. Aliquam sed velit eget eros fringilla pharetra. Etiam id placerat arcu. Quisque placerat tellus quis diam bibendum tristique. Aenean ut elit et lacus sodales auctor vel eget nibh.

Proin tincidunt ante est, at pharetra odio fermentum quis. Ut accumsan pulvinar fringilla. Duis arcu massa, placerat at ante at, consectetur blandit ante. Quisque dui tortor, feugiat et ipsum quis, accumsan efficitur lectus. Sed commodo ante id semper feugiat. Vivamus nisi metus, efficitur eu mollis quis, tempor ut sem. Praesent sed sem vel sem rhoncus sollicitudin. Mauris egestas malesuada nisi, sit amet elementum dolor faucibus sed. Suspendisse placerat urna a lacus viverra vulputate.

Vestibulum ut dignissim purus, varius posuere leo. Nunc hendrerit dui dui, non faucibus risus fringilla nec. Praesent facilisis purus quis risus ullamcorper, vitae ultrices magna pellentesque. Nullam tristique tellus non cursus molestie. Integer ut ligula a velit sagittis gravida. Praesent gravida vitae turpis vitae congue. Curabitur elit leo, rhoncus non lobortis sit amet, sodales nec neque. Proin in ex turpis. Phasellus ullamcorper viverra sagittis. Donec vehicula ac nibh ut euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam ultricies pellentesque justo quis sollicitudin. Mauris id porttitor elit.

Etiam tempus sapien nec nibh ornare, sit amet consectetur libero dapibus. Mauris bibendum, dui ut bibendum bibendum, ligula eros iaculis libero, quis malesuada velit purus et neque. Pellentesque porta vehicula elit non elementum. Donec sed hendrerit magna, eget sagittis dolor. Mauris convallis eu purus a pulvinar. Nullam congue magna tellus, vel congue nibh iaculis vitae. Nam gravida urna finibus sapien blandit, quis eleifend eros consectetur. Proin iaculis ante non porta consectetur.

Ut condimentum nibh elit, at tristique nisl suscipit id. Proin mollis non nulla et tristique. Proin in mauris erat. Nunc sit amet odio ultricies, facilisis ante et, imperdiet massa. Fusce in maximus risus. Pellentesque et lorem nec nunc iaculis maximus. Donec consequat facilisis dolor ut finibus. Aenean vitae mollis risus. In lacinia a ipsum a lacinia.

Nam lacinia varius sollicitudin. Nunc maximus mauris eu cursus efficitur. Phasellus ac malesuada arcu. Morbi convallis tincidunt semper. Cras id iaculis nibh. Vestibulum gravida odio id porta viverra. Fusce quam felis, lacinia eu justo sed, semper ornare mauris. Curabitur nec risus leo. Morbi eleifend sit amet elit eu sagittis. Pellentesque dapibus porta sapien, sed laoreet est molestie eget. Vestibulum massa risus, pellentesque et suscipit et, accumsan et ante. Duis eu egestas neque, non tempor tortor. Fusce viverra dolor at erat posuere congue. Duis cursus a metus at posuere.

Sed sit amet pharetra lacus. Vestibulum lacinia nec nibh a rutrum. Pellentesque luctus metus eget tempor fermentum. Cras sit amet nulla vel nisi imperdiet semper. Duis a pretium tortor, et faucibus risus. Suspendisse eget hendrerit magna. Praesent commodo hendrerit ante, id lacinia purus imperdiet at.

Curabitur ut orci porta tellus pharetra tincidunt. Nam non felis nec diam sollicitudin convallis nec non enim. Etiam volutpat quam quis lacus porta, et maximus lorem tempus. Quisque dignissim elit in fermentum faucibus. Cras malesuada arcu non est tempor, nec tincidunt velit pretium. Nam commodo, leo pretium fermentum tempus, massa magna iaculis enim, vel ornare enim elit et justo. Proin dignissim pellentesque dui, ut tincidunt nibh varius eu. Donec erat diam, hendrerit quis velit ac, interdum efficitur sapien. Vivamus facilisis malesuada libero, ac posuere lectus. Cras eget quam in nunc aliquam convallis. Donec tristique consectetur eros, non semper leo suscipit sit amet. Curabitur nec est nec tellus pretium pretium quis vitae felis. Mauris non aliquam odio, a vehicula quam. Praesent elementum ligula non porta sodales.

Integer dictum eros ac massa pharetra laoreet. Pellentesque sollicitudin scelerisque sodales. Sed faucibus arcu ac nisi imperdiet, nec fermentum justo mollis. Nunc fermentum porttitor purus, vitae pretium odio facilisis a. Pellentesque euismod maximus mauris, ac dictum elit lacinia ac. Maecenas non purus nibh. Mauris luctus porta libero, vel interdum risus ornare in. Sed mattis libero non risus condimentum, in varius neque gravida. Sed eget aliquet nisi. Sed condimentum consequat pellentesque. Sed a libero rutrum, aliquet mauris quis, condimentum lectus. Nullam rhoncus sed velit sit amet fermentum. Vivamus congue auctor pharetra. Nulla quis urna nec metus mattis iaculis eu a magna. Aliquam pretium lacinia dui sit amet scelerisque. Vestibulum nec egestas ipsum.

Maecenas nec vestibulum tellus, vel lobortis velit. Cras iaculis nunc augue, sit amet molestie neque convallis vitae. Etiam nec sem at lectus finibus accumsan. Sed id auctor libero. Vestibulum egestas, ante et vulputate placerat, lorem ante pharetra metus, id finibus felis felis vitae ante. Ut mollis maximus sodales. Aliquam in arcu malesuada, pretium magna sed, aliquet nunc. Vivamus luctus, nunc in vestibulum finibus, augue elit consectetur est, ac consequat tortor est id metus.

Duis iaculis ullamcorper urna, et interdum tellus facilisis a. Curabitur ac nibh vel purus condimentum hendrerit. Fusce volutpat ante velit, a dapibus ipsum suscipit nec. In hac habitasse platea dictumst. Integer posuere sapien et diam rhoncus pulvinar. Nam condimentum metus mollis augue vehicula, ut aliquet velit luctus. Proin interdum vestibulum orci, sit amet pretium nibh fringilla a. Donec hendrerit libero felis, sed vehicula felis facilisis at. Proin nec iaculis lacus. Sed tempor, augue sed euismod mollis, felis odio blandit dolor, sed mollis diam arcu vel orci.

Fusce bibendum viverra nunc, et facilisis enim vestibulum id. Pellentesque felis lectus, tempor sit amet augue eu, congue placerat dui. Sed facilisis pulvinar risus, vel rutrum felis mattis eu. Sed ante ligula, lobortis in suscipit nec, dictum sed tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In et sem finibus, congue ligula ut, sagittis lacus. Curabitur aliquet eget massa ut pretium. Curabitur lobortis purus eu justo viverra, sodales rhoncus augue malesuada. Vivamus ullamcorper risus nec tortor aliquet tincidunt. Sed id est et magna mattis blandit. Aenean bibendum dignissim volutpat. Etiam eu nunc sit amet ipsum mattis mattis et ac libero. Donec accumsan risus a nibh iaculis luctus. Aenean ac est quam.

Etiam eros turpis, viverra eget pharetra sed, sodales vel justo. Nam tortor diam, vulputate sit amet ultricies a, congue quis lorem. Vivamus fringilla at ligula eu efficitur. In non felis in ante placerat vestibulum. Nam placerat at risus ac mattis. Morbi vestibulum aliquam mauris nec congue. Praesent id dignissim odio, ut auctor sapien.

Praesent blandit facilisis viverra. Phasellus pharetra libero vitae neque auctor pharetra. Aenean scelerisque tincidunt ultricies. In et sem vitae diam varius ultricies nec in quam. Maecenas id nulla eget velit condimentum tristique. Curabitur vel leo ut turpis ornare suscipit. Mauris placerat libero eu elementum consequat.

Nam feugiat neque vitae arcu accumsan, eu efficitur massa hendrerit. In in neque eleifend, molestie ligula in, facilisis metus. Etiam fringilla vestibulum est, id ornare eros accumsan in. Etiam sagittis dolor nisl, ac elementum nisi sollicitudin ut. Sed at velit tincidunt, maximus lacus consectetur, pharetra mi. Etiam tincidunt mi tellus, nec sodales purus finibus at. Phasellus ultricies nisi id lorem aliquam, vel tempus eros imperdiet. Duis vitae ex metus. Integer nec interdum nisl. Morbi vehicula sem et mi blandit, nec consectetur mi pulvinar. Etiam at gravida odio. Nunc ligula tellus, luctus auctor eleifend ut, suscipit eget quam. Fusce quam sem, fringilla vitae libero eget, tempus suscipit augue. Sed tellus risus, lobortis in nunc et, feugiat lacinia quam. Mauris rhoncus turpis ac sem mattis, in varius lacus hendrerit.
</div>
    );
}

export default About;